### ISSUE TITLE
ParseError isn't exposed

### ISSUE THREAD

**Issue by bmc-msft** [cole14/rust-elf#20]
As `open_stream` returns `ParseError`, it would be useful if ParseError was itself public such that users can appropriately understand and respond to the different underlying parsing errors.

https://github.com/cole14/rust-elf/blob/471729fee3c3e5089b2c11545045bff360bc3c7c/src/file.rs#L15

**Comment by cole14** [comment]
I've released crate v0.3.0 which includes this change.

v0.3.0 also contains various interface changes in order to make the parser zero-alloc and lazy in its parsing. A quick look at your usage in the linked `avml` crate makes me think that'll help speed things up a bit, since it looks like you're only needing to inspect the segments (program headers).

I'm going to keep this open so you can verify this change works for you. Let me know if you'd like any help adjusting your usage to the updated interface. I think you'll mostly just want to wrap the `image.src` in a `CachedReadBytes` to provide to `open_stream()`, and a change to how you filter the phdrs. If you want to keep them in a vec, you can try something like:

```
let segments: Vec<segment::ProgramHeader> = file
            .segments()
            .expect("Failed to read segments")
            .filter(|x| x.p_type == segment::ProgType(gabi::PT_LOAD))
            .collect();
```
