### ISSUE TITLE
Typo in src/parse.rs l.161

### ISSUE THREAD

**Issue by lfalkau** [cole14/rust-elf#32]
Hello,

Nothing very important, but I think you have a typo in src/parse.rs at line 161. You open the range with a square bracket and close it with a parenthesis:

```rs
write!(f, "Could not read bytes in range [{start:#X}, {end:#X})")
```

Which prints something like:
```
Could not read bytes in range [0x0, 0x10)
```

**Comment by cole14** [comment]
Hello, thanks for noticing this and raising an issue!

It actually is intended, though maybe a little confusing. I'm using [mathematical interval notation](https://en.wikipedia.org/wiki/Interval_(mathematics)) here to say that the byte range being read is a half-open interval. This is because the underlying slice-get call is using a [Range](https://doc.rust-lang.org/core/ops/struct.Range.html), which is a half-open interval. The bytes being read include the starting offset, but end at and exclude the ending offset.

**Comment by cole14** [comment]
Yup not a problem, and thanks for bring it up!
